name: fidbee_utils
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  package_info: ^0.4.0+18
  autostart: ^0.0.1
  app_settings: ^4.1.0
  page_transition: ^1.1.7+2
  responsive_framework: ^0.0.14
  logger: ^0.9.4
  animations: ^1.1.2
  cached_network_image: ^2.2.0+1
  flutter_staggered_grid_view: ^0.3.0
  flutter_banner_swiper: ^0.1.4
  datetime_picker_formfield: ^1.0.0
  pull_to_refresh: ^1.6.4
  auto_size_text: ^2.1.0
  firebase_messaging: ^7.0.3
  flutter_local_notifications: ^1.4.4+2
  cloud_firestore: 0.14.3
  fluttertoast: ^4.0.1
  sqflite: ^1.3.0+1
  url_launcher: ^5.4.10
  shared_preferences: ^0.5.7+3
  intl: ^0.16.1
  after_layout: ^1.0.7+2
  device_unlock: ^1.1.2
  flutter_typeahead: ^1.8.1
  http: ^0.12.2
  permission_handler: ^5.0.0+hotfix.8
  share: ^0.6.4+3
  photo_view: ^0.9.2
  firebase_auth: ^0.18.3
  image_picker: ^0.6.6+4
  html: ^0.14.0+3
  image_downloader: ^0.19.2
  bubble_tab_indicator: ^0.1.4
  equatable: ^1.2.0
  in_app_update: ^2.0.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  path_provider: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
